language: php

# dist: xenial

# git:
#     depth: 2

matrix:
    include:
        - php: 7.4
        #- php: nightly
    fast_finish: true

before_install:
    - |
      # Enable extra ppa
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
      sudo add-apt-repository -y ppa:ondrej/php
      sudo rm /etc/apt/sources.list.d/google-chrome.list
      sudo rm /etc/apt/sources.list.d/mongodb-3.4.list
      sudo apt update

before_script: composer require --dev phpunit/phpunit ^9.3
script: vendor/bin/phpunit

# script:
#     echo $TRAVIS_PHP_VERSION $php_extra | xargs -n1 bash -c '(</dev/tty run_tests $0)' || false
