language: php

# dist: xenial

git:
    depth: 2

matrix:
    include:
        - php: 7.4
        #- php: nightly
    fast_finish: true

before_script: composer require --dev phpunit/phpunit ^9.3

script: vendor/bin/phpunit

after_failure: 
    - ./after_failure.sh
