language: php

# dist: xenial

git:
    depth: 2

matrix:
    include:
        - php: 7.4
        #- php: nightly
    fast_finish: true

before_script: composer require --dev phpunit/phpunit ^9.3

script: vendor/bin/phpunit

#after_failure: curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token curl -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues -d "{\"title\":\"[Travis ci] Build failed\"}"
